BEGIN;

DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS employees CASCADE;
DROP TABLE IF EXISTS departments CASCADE;

CREATE TABLE departments (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    name varchar(50) NOT NULL,
    created_by_user_id integer NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone,
    updated_by_user_id integer,
    CONSTRAINT departments_pk PRIMARY KEY (id),
    CONSTRAINT departments_name_uk UNIQUE (name)
);

CREATE TABLE employees (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    employee_no varchar(10) NOT NULL,
    name varchar(50) NOT NULL,
    email varchar(100),
    hire_date date NOT NULL,
    department_id integer NOT NULL,
    created_by_user_id integer NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone,
    updated_by_user_id integer,
    CONSTRAINT employees_pk PRIMARY KEY (id),
    CONSTRAINT employees_employee_no_uk UNIQUE (employee_no)
);

CREATE TABLE users (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    login_id varchar(50) NOT NULL,
    password varchar(255) NOT NULL,
    employee_id integer NOT NULL,
    CONSTRAINT users_pk PRIMARY KEY (id),
    CONSTRAINT users_login_id_uk UNIQUE (login_id),
    CONSTRAINT users_employee_id_uk UNIQUE (employee_id)
);

ALTER TABLE employees
    ADD CONSTRAINT employees_departments_fk
    FOREIGN KEY (department_id)
    REFERENCES departments (id)
    ON DELETE RESTRICT
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE employees
    ADD CONSTRAINT employees_created_by_users_fk
    FOREIGN KEY (created_by_user_id)
    REFERENCES users (id)
    ON DELETE RESTRICT
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE employees
    ADD CONSTRAINT employees_updated_by_users_fk
    FOREIGN KEY (updated_by_user_id)
    REFERENCES users (id)
    ON DELETE RESTRICT
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE departments
    ADD CONSTRAINT departments_created_by_users_fk
    FOREIGN KEY (created_by_user_id)
    REFERENCES users (id)
    ON DELETE RESTRICT
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE departments
    ADD CONSTRAINT departments_updated_by_users_fk
    FOREIGN KEY (updated_by_user_id)
    REFERENCES users (id)
    ON DELETE RESTRICT
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE users
    ADD CONSTRAINT users_employees_fk
    FOREIGN KEY (employee_id)
    REFERENCES employees (id)
    ON DELETE RESTRICT
    DEFERRABLE INITIALLY DEFERRED;

COMMIT;
